allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  agent-browser: true
  sharp: true
  unrs-resolver: true
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - 'agent-browser'
  - 'sharp'
  - 'unrs-resolver'
