import './global.css';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<>
			<html lang='en' data-mode='dark'>
				<body className='bg-primary-50 dark:bg-primary-950'>{children}</body>
			</html>
		</>
	);
}
